object:
  _target_:           tiny_augment.model.build_model
  backbone:           edgenext_base.in21k_ft_in1k
  num_classes:        2
  pretrained:         true
  finetune_mode:      partial
  trainable_prefixes: 
                      - head
                      - stages.3
                      - stages.2
  device_type:        cpu

pretrain_img_size:    256
last_checkpoint:      null
compile_mode:         reduce-overhead
