defaults:
  - base

object:
  backbone:           edgenext_base.in21k_ft_in1k
  pretrained:         false
  trainable_prefixes: 
                      - head
                      - stages.3

<<<<<<< HEAD
model_path:
  mlflow_run_id:      null
  artifact_path:      null
  local_checkpoint_path: null

pretrain_img_size:    256
compile_mode:         reduce-overhead
=======
model_path:           null
>>>>>>> origin/fomin-cv-pipeline
