object:
  _target_:           tiny_augment.model.build_model
  backbone:           eva02_small_patch14_336.mim_in22k_ft_in1k
  num_classes:        2
  pretrained:         true
  finetune_mode:      partial
  trainable_prefixes: 
                      - head
                      - fc_norm
                      - blocks.8
                      - blocks.9
                      - blocks.10
                      - blocks.11
  device_type:        cuda:0

pretrain_img_size:    336
last_checkpoint:      null
compile_mode:         reduce-overhead