export const endpoints = {
  datasetsCatalog: '/datasets',
  activateDataset: (datasetId: string) => `/datasets/${datasetId}/activate`,
  jobs: '/jobs',
  cancelJob: (jobId: string) => `/jobs/${jobId}/cancel`,
  initUpload: '/uploads/init',
  uploadChunk: (uploadId: string, partNumber: number, totalParts: number) =>
    `/uploads/${uploadId}/parts?partNumber=${partNumber}&totalParts=${totalParts}`,
  completeUpload: (uploadId: string) => `/uploads/${uploadId}/complete`,
  uploadDataset: '/sessions/upload',
  restoreSession: (sessionId: string) => `/sessions/${sessionId}`,
  taskStatus: (sessionId: string, taskId: string) => `/sessions/${sessionId}/tasks/${taskId}`,
  datasetStats: (sessionId: string) => `/sessions/${sessionId}/dataset/stats`,
  selectClasses: (sessionId: string) => `/sessions/${sessionId}/dataset/classes`,
  syncWorkflowState: (sessionId: string) => `/sessions/${sessionId}/workflow/state`,
  startFineTune: (sessionId: string) => `/sessions/${sessionId}/diffusion/fine-tune`,
  generationDefaults: (sessionId: string) => `/sessions/${sessionId}/generation/config`,
  startGeneration: (sessionId: string) => `/sessions/${sessionId}/generation`,
  getModificationSource: (sessionId: string) => `/sessions/${sessionId}/modification/source`,
  startModification: (sessionId: string) => `/sessions/${sessionId}/modification`,
  generationResults: (sessionId: string) => `/sessions/${sessionId}/results`,
  approveAsset: (sessionId: string, assetId: string) => `/sessions/${sessionId}/results/${assetId}/approve`,
  rejectAsset: (sessionId: string, assetId: string) => `/sessions/${sessionId}/results/${assetId}/reject`,
  startClassifierTraining: (sessionId: string) => `/sessions/${sessionId}/classifier/train`,
  getMetrics: (sessionId: string) => `/sessions/${sessionId}/metrics`,
  getDownload: (sessionId: string) => `/sessions/${sessionId}/download`,
  fileByPath: '/assets',
  workflowSocket: (sessionId: string) => `/sessions/${sessionId}/stream`,
}
