_target_:         tiny_augment.dataset.build_dataloaders

train_root:       ${project_root}/data/pretrain/train
val_root:         ${project_root}/data/pretrain/val
    
transforms:    
  _target_:       tiny_augment.augmentations.get_augmentations
  img_size:       ${model.pretrain_img_size}

train_batch_size: 32
val_batch_szie:   64

sampler_type:     balanced
num_workers:      8
weights_root:     null
