dataloaders:
  _target_:     src.dataset.build_loaders

  train_root:   ../data/fine_tune/train
  val_root:     ../data/fine_tune/val

  transforms:
    _target_:   augmentations.get_augmentations
    img_size:   ${model.img_size}

  sampler_type: weighted
  weights_root: ../data/fine_tune/weights.csv