_target_:         torch.optim.lr_scheduler.SequentialLR

schedulers:
  - _target_:     torch.optim.lr_scheduler.LinearLR
    start_factor: 0.1
    end_factor:   1.0
    total_iters:  1000

  - _target_:     torch.optim.lr_scheduler.CosineAnnealingLR
    T_max:        9000

milestones:       [1000]