mlflow:
  experiment_name: AAA-pretrain
  run_name:        null
  description:     Fine-tuning on ISIC-like dataset
  nested:          false
  tags:
    stage:         finetune
    dataset:       ISIC
    backbone:      ${model.object.backbone}