mlflow:
  experiment_name: "AAA-pretrain"
  run_name:        null
  description:     "Pretraining on ISIC dataset"
  nested:          false
  tags: 
    stage:         pretrain
    dataset:       ISIC
    backbone:      ${model.object.backbone}