defaults:
  - _self_
  - model:        EdgeNeXt_finetune
  - dataloader:   fine_tune
  - optimizer:    Adam
  - scheduler:    CosineAnnealingLR
  - logger:       mlflow_finetune

hydra:
  run:
    dir:          ../outputs/fine_tune/${now::%Y-%m-%d_%H-%M}

train:
  epochs:         500
  checkpoint_dir: ${hydra:runtime.output_dir}/checkpoints/{model.object.backbone}

project_root:     ${hydra:runtime.cwd}
