defaults:
  - _self_
  - model:        EdgeNeXt_finetune
  - criterion:    focal_loss
  - dataloader:   fine_tune
  - optimizer:    AdamW
  - scheduler:    CosineAnnealingLR
  - logger:       mlflow_finetune
  - train:        train

hydra:
  run:
    dir:          ${hydra:runtime.cwd}/outputs/fine_tune/${now::%Y-%m-%d_%H-%M}

project_root:     ${hydra:runtime.cwd}
