defaults:
  - _self_
  - model:        EdgeNeXt_pretrain
  - dataloader:   pretrain
  - optimizer:    Adam
  - scheduler:    CosineAnnealingLR
  - logger:       mlflow_pretrain

hydra:
  run:
    dir:          ../outputs/pretrain/${now::%Y-%m-%d_%H-%M}

train:
  epochs:         500
  checkpoint_dir: ${hydra:runtime.output_dir}/checkpoints/{model.object.backbone}

project_root:     ${hydra:runtime.cwd}