defaults:
  - _self_
  - model:        EdgeNeXt_pretrain
  - criterion:    focal_loss
  - dataloader:   pretrain
  - optimizer:    AdamW
  - scheduler:    CosineAnnealingLR
  - logger:       mlflow_pretrain
  - train:        train

hydra:
  run:
    dir:          ${hydra:runtime.cwd}/outputs/pretrain/${now:%Y-%m-%d_%H-%M}

project_root:     ${hydra:runtime.cwd}