object:
  _target_:        src.models.build_model
  backbone:        edgenext_base.in21k_ft_in1k
  num_classes:     2
  pretrained:      false

checkpoint:
  mlflow_run_id:   null
  artifact_path:   null

pretrain_img_size: 256